### ISSUE TITLE
Add title attributes to the one-letter toggle buttons

### ISSUE THREAD

**Issue by roryokane** [talex5/cuekeeper#6]
The “✓ n w f ★” buttons are hard to use if you don’t know what they do. I would expect hovering over them with the mouse to show their full name. For example, the “f” button should show “future” or “mark as for future”. You can implement this by adding `title="future"` to the `a` element.

I think you can implement this by changing the function [`toggle_label`](https://github.com/talex5/cuekeeper/blob/cf86e20761f650a17c0484019d550711cb8533b5/js/ck_template.ml#L166), or perhaps `make_toggles` below it.

**Comment by talex5** [comment]
Good idea - done!
