### ISSUE TITLE
Allow cancelling editing with the Esc key

### ISSUE THREAD

**Issue by roryokane** [talex5/cuekeeper#7]
Allowing cancellation of in-progress actions with the Esc key makes it nicer to explore the UI, because can click on unfamiliar controls without worrying that the UI state will be changed in a hard-to-undo manner.

When you click on the title of an action, it is replaced with a text field so you can edit it. If you think the current name is okay after all, you should be able to hit the Esc key to convert the text field back into a static label. Right now, you have to close the action box with the X in the top-right and open it again to return to the previous state.

Another example: if you click on an area or context within an action box, a drop-down menu appears so you can choose a new value. You can currently close it by clicking in empty space out of the menu. It would be nice if you could also press Esc to close the menu.

**Comment by talex5** [comment]
Esc works for me to close context menus (and should work for all modals; see https://github.com/talex5/cuekeeper/blob/10fec5958c45f5e494df6eaeab707f0de6c21b97/js/ck_modal.ml#L48).

Have fixed it for editing titles, though - thanks!
